version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout

      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json"}}
          - v1-dependencies-

      - run: yran install

      - save_cache:
          paths: 
            - node_modulaes 
          key: v1-dependencies-{{ checksum "package.json"}}
      - run: yarn test 
